# Generated by Django 5.1 on 2024-12-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBuddyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(default='Goal', max_length=20),
        ),
    ]
