# Generated by Django 5.1 on 2024-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBuddyApp', '0002_user_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
